name: flashchat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.4
  fluttertoast: ^7.1.6
  image_picker: ^0.6.7+17
  shared_preferences: ^0.5.12+4
  firebase_storage: ^5.2.0
  cached_network_image: ^2.4.1
  intl: ^0.16.1
  photo_view: ^0.10.3
  firebase_core: ^0.5.3
  provider: ^4.3.2+3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/customIcons.ttf


  assets:
    - assets/images/google.png
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
